---
services:
  mattermost:
    image: mattermost/mattermost-preview
    ports:
      - 8065:8065
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2000M
        reservations:
          memory: 200M
volumes:
  pgdata:
